services:
  django-backend-dev-https:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: django-backend-dev-https
    depends_on:
      - postgres-db-dev
    env_file:
      - ".env"
    volumes:
      - "./backend:/backend"
      - "./backend/staticfiles:/backend/staticfiles"
    command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 sheriff_crandy_project.wsgi:application"]      
    networks:
      - "sc_backend_dev"

  vuejs-frontend-dev-https:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vuejs-frontend-dev-https
    env_file:
      - "./frontend/.env"
    volumes:
      - "./frontend:/frontend"
      - "node_modules:/frontend/node_modules"
    command: ["sh", "-c", "npm run build"]
    depends_on:
      - django-backend-dev-https
    networks:
      - "sc_backend_dev"      

  nginx-dev-https:
    image: nginx:latest
    container_name: nginx-dev-https
    ports:
      - "443:443"
    restart: always      
    volumes:
      - ./nginx/dev-https-nginx.conf:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/certs/:ro
      - ./backend/staticfiles:/backend/staticfiles
      - ./frontend/dist:/frontend/dist
    depends_on:
      - ssl-cert-https-dev-gen
      - django-backend-dev-https
      - vuejs-frontend-dev-https
    networks:
      - "sc_backend_dev"

  ssl-cert-https-dev-gen:
    image: alpine:latest
    container_name: ssl-cert-https-dev-gen
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    command: >
      sh -c "
      apk add --no-cache openssl && \
      if [ ! -f /etc/nginx/certs/sc.local.crt ]; then
        echo 'Generating self-signed SSL certificate...';
        mkdir -p /etc/nginx/certs && \
        openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/nginx/certs/sc.local.key -out /etc/nginx/certs/sc.local.crt -days 365 -subj '/C=US/ST=Idaho/L=Boise/O=sc/OU=scou/CN=sc.local/emailAddress=lctechnology@protonmail.com';
      else
        echo 'SSL certificate already exists. Skipping generation.';
      fi"     

# networks:
#   sc_backend:
#     driver: bridge

networks:
  sc_backend_dev:
    external: true

volumes:
  sc_postgres_data_dev:
    external: true
  node_modules: