services:
  django-backend-dev-http:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: django-backend-dev-http
    ports:
      - "8000:8000"
    depends_on: 
      - postgres-db-dev-http      
    env_file:
      - ".env"
    volumes:
      - "./backend:/backend"
    # command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && DJANGO_SETTINGS_MODULE=sheriff_crandy_project.dev_settings python manage.py runserver 0.0.0.0:8000"]
    command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py migrate && DJANGO_SETTINGS_MODULE=sheriff_crandy_project.dev_settings python manage.py runserver 0.0.0.0:8000"]
    networks:
      - "sc_backend"

  vuejs-frontend-dev-http:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vuejs-frontend-dev-http
    ports:
      - "8080:8080"
    env_file:
      - "./frontend/.env"
    volumes:
      - "./frontend:/frontend"
    command: ["sh", "-c", "npm run serve"]

  postgres-db-dev-http:
    image: postgres:17
    environment: 
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sc_postgres_data:/var/lib/postgresql/data
  

volumes:
  sc_postgres_data:

networks:
  sc_backend:
    driver: bridge