# Generated by Django 4.2 on 2023-07-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flps_app', '0001_initial'),
        ('tracks_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('statePref', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('date_order_created', models.DateTimeField(auto_now=True)),
                ('usd_paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('jpy_paid_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('free_download', models.BooleanField(blank=True, default=False, null=True)),
                ('stripe_token', models.CharField(blank=True, max_length=100, null=True)),
                ('flp', models.ManyToManyField(blank=True, default=None, related_name='flp_orders', to='flps_app.flp')),
                ('track', models.ManyToManyField(blank=True, default=None, related_name='track_orders', to='tracks_app.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
