# Generated by Django 5.2.8 on 2025-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flps_app', '0001_initial'),
        ('order_app', '0001_initial'),
        ('tracks_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('statePref', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('date_order_created', models.DateTimeField(auto_now=True)),
                ('usd_paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('jpy_paid_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('free_download', models.BooleanField(blank=True, default=False, null=True)),
                ('stripe_token', models.CharField(blank=True, max_length=100, null=True)),
                ('flp', models.ManyToManyField(blank=True, default=None, related_name='anon_flp_orders', to='flps_app.flp')),
                ('track', models.ManyToManyField(blank=True, default=None, related_name='anon_track_orders', to='tracks_app.track')),
            ],
            options={
                'verbose_name': 'AnonOrder',
                'verbose_name_plural': 'AnonOrders',
                'db_table': 'anon_orders',
            },
        ),
    ]
