# Generated by Django 5.2.8 on 2025-11-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_anonorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonorder',
            options={'verbose_name': 'Anon Order', 'verbose_name_plural': 'AnonOrders'},
        ),
    ]
