# Generated by Django 4.2 on 2023-06-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lctec_user', '0003_alter_cart_flps_in_cart_alter_cart_tracks_in_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lctec_user',
            options={'verbose_name': 'users', 'verbose_name_plural': 'Users'},
        ),
    ]
